[package]
name = "anvimator"
version = "0.1.0"
edition = "2021"

[dependencies]
swash = "0.1.8"
png = "0.17.9"
thiserror = "1.0.44"
env_logger = "0.10.0"
log = "0.4.19"
termcolor = "1.2.0"
rmpv = "1.0.1"
winit = "0.28.6"
wgpu = "0.17.0"
pollster = "0.3.0"
bytemuck = { version = "1.13.1", features = ["derive"] }

[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga" }
