[package]
name = "neophyte"
version = "0.1.1"
edition = "2021"
authors = ["Tim Harding"]
repository = "https://github.com/tim-harding/neophyte"
license = "MIT"
keywords = ["neovim"]
categories = ["text-editors", "gui", "development-tools"]
description = "A WebGPU rendered Neovim GUI"

[dependencies]
swash = "0.1.8"
thiserror = "1.0.44"
env_logger = "0.10.0"
log = "0.4.19"
rmpv = "1.0.1"
winit = "0.28.6"
wgpu = "0.17.0"
pollster = "0.3.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
font-loader = "0.11.0"

# Temporary patch to address miscompilation with non-uniform indexing
# https://github.com/gfx-rs/wgpu/issues/4029
[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga" }

# Compile dependencies in release mode but Neophyte in development
[profile.dev.package."*"]
opt-level = 3
