[package]
name = "anvimator"
version = "0.1.0"
edition = "2021"

[dependencies]
rusttype = "0.9.3"
png = "0.17.9"
thiserror = "1.0.44"
env_logger = "0.10.0"
log = "0.4.19"
termcolor = "1.2.0"
rmpv = "1.0.1"
